title: "pyDecNef"
tagline: "Decoded Neurofeedback with Python"
description: "A Python framework for real-time fMRI decoded neurofeedback"
remote_theme: just-the-docs/just-the-docs

# Set logo
logo: "/assets/images/logo.png"

# Set favicon
favicon: "/assets/images/favicon.ico"

# Aux links for the upper right navigation
aux_links:
  "pyDecNef repository on GitHub":
    - "//github.com/pedromargolles/pyDecNef"

# Color scheme
color_scheme: decnef_color

# Makes Aux links open in a new tab
aux_links_new_tab: true

# SEO
twitter:
  username: pedromargolles
  card: summary_large_image

# Open Graph Image
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/images/social_card.png"
