title: "pyDecNef"
remote_theme: just-the-docs/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "pyDecNef repository on GitHub":
    - "//github.com/pedromargolles/pyDecNef"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
